# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.24

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.24.1/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.24.1/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/kuberlog/tree

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/kuberlog/tree

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.24.1/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.24.1/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/opt/homebrew/Cellar/cmake/3.24.1/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/opt/homebrew/Cellar/cmake/3.24.1/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/opt/homebrew/Cellar/cmake/3.24.1/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/opt/homebrew/Cellar/cmake/3.24.1/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/opt/homebrew/Cellar/cmake/3.24.1/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/opt/homebrew/Cellar/cmake/3.24.1/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/kuberlog/tree/CMakeFiles /Users/kuberlog/tree//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/kuberlog/tree/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named -tree-

# Build rule for target.
-tree-: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 -tree-
.PHONY : -tree-

# fast build rule for target.
-tree-/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/-tree-.dir/build.make CMakeFiles/-tree-.dir/build
.PHONY : -tree-/fast

#=============================================================================
# Target rules for targets named http

# Build rule for target.
http: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 http
.PHONY : http

# fast build rule for target.
http/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/http.dir/build.make CMakeFiles/http.dir/build
.PHONY : http/fast

#=============================================================================
# Target rules for targets named kcc

# Build rule for target.
kcc: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 kcc
.PHONY : kcc

# fast build rule for target.
kcc/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kcc.dir/build.make CMakeFiles/kcc.dir/build
.PHONY : kcc/fast

#=============================================================================
# Target rules for targets named Cyborg

# Build rule for target.
Cyborg: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Cyborg
.PHONY : Cyborg

# fast build rule for target.
Cyborg/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cyborg.dir/build.make CMakeFiles/Cyborg.dir/build
.PHONY : Cyborg/fast

#=============================================================================
# Target rules for targets named Empire

# Build rule for target.
Empire: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Empire
.PHONY : Empire

# fast build rule for target.
Empire/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Empire.dir/build.make CMakeFiles/Empire.dir/build
.PHONY : Empire/fast

#=============================================================================
# Target rules for targets named Alpha

# Build rule for target.
Alpha: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Alpha
.PHONY : Alpha

# fast build rule for target.
Alpha/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Alpha.dir/build.make CMakeFiles/Alpha.dir/build
.PHONY : Alpha/fast

#=============================================================================
# Target rules for targets named space_clean

# Build rule for target.
space_clean: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 space_clean
.PHONY : space_clean

# fast build rule for target.
space_clean/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/space_clean.dir/build.make CMakeFiles/space_clean.dir/build
.PHONY : space_clean/fast

#=============================================================================
# Target rules for targets named test_space_clean

# Build rule for target.
test_space_clean: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_space_clean
.PHONY : test_space_clean

# fast build rule for target.
test_space_clean/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_space_clean.dir/build.make CMakeFiles/test_space_clean.dir/build
.PHONY : test_space_clean/fast

#=============================================================================
# Target rules for targets named zlib

# Build rule for target.
zlib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 zlib
.PHONY : zlib

# fast build rule for target.
zlib/fast:
	$(MAKE) $(MAKESILENT) -f _deps/zlib-build/CMakeFiles/zlib.dir/build.make _deps/zlib-build/CMakeFiles/zlib.dir/build
.PHONY : zlib/fast

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) $(MAKESILENT) -f _deps/curl-build/CMakeFiles/uninstall.dir/build.make _deps/curl-build/CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named libcurl

# Build rule for target.
libcurl: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 libcurl
.PHONY : libcurl

# fast build rule for target.
libcurl/fast:
	$(MAKE) $(MAKESILENT) -f _deps/curl-build/lib/CMakeFiles/libcurl.dir/build.make _deps/curl-build/lib/CMakeFiles/libcurl.dir/build
.PHONY : libcurl/fast

#=============================================================================
# Target rules for targets named cpr

# Build rule for target.
cpr: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cpr
.PHONY : cpr

# fast build rule for target.
cpr/fast:
	$(MAKE) $(MAKESILENT) -f _deps/cpr-build/cpr/CMakeFiles/cpr.dir/build.make _deps/cpr-build/cpr/CMakeFiles/cpr.dir/build
.PHONY : cpr/fast

#=============================================================================
# Target rules for targets named gmock

# Build rule for target.
gmock: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock
.PHONY : gmock

# fast build rule for target.
gmock/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googlemock/CMakeFiles/gmock.dir/build.make _deps/googletest-build/googlemock/CMakeFiles/gmock.dir/build
.PHONY : gmock/fast

#=============================================================================
# Target rules for targets named gmock_main

# Build rule for target.
gmock_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock_main
.PHONY : gmock_main

# fast build rule for target.
gmock_main/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googlemock/CMakeFiles/gmock_main.dir/build.make _deps/googletest-build/googlemock/CMakeFiles/gmock_main.dir/build
.PHONY : gmock_main/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googletest/CMakeFiles/gtest.dir/build.make _deps/googletest-build/googletest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googletest/CMakeFiles/gtest_main.dir/build.make _deps/googletest-build/googletest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

Alpha.o: Alpha.cpp.o
.PHONY : Alpha.o

# target to build an object file
Alpha.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Alpha.dir/build.make CMakeFiles/Alpha.dir/Alpha.cpp.o
.PHONY : Alpha.cpp.o

Alpha.i: Alpha.cpp.i
.PHONY : Alpha.i

# target to preprocess a source file
Alpha.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Alpha.dir/build.make CMakeFiles/Alpha.dir/Alpha.cpp.i
.PHONY : Alpha.cpp.i

Alpha.s: Alpha.cpp.s
.PHONY : Alpha.s

# target to generate assembly for a file
Alpha.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Alpha.dir/build.make CMakeFiles/Alpha.dir/Alpha.cpp.s
.PHONY : Alpha.cpp.s

Cyborg.o: Cyborg.cpp.o
.PHONY : Cyborg.o

# target to build an object file
Cyborg.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cyborg.dir/build.make CMakeFiles/Cyborg.dir/Cyborg.cpp.o
.PHONY : Cyborg.cpp.o

Cyborg.i: Cyborg.cpp.i
.PHONY : Cyborg.i

# target to preprocess a source file
Cyborg.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cyborg.dir/build.make CMakeFiles/Cyborg.dir/Cyborg.cpp.i
.PHONY : Cyborg.cpp.i

Cyborg.s: Cyborg.cpp.s
.PHONY : Cyborg.s

# target to generate assembly for a file
Cyborg.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cyborg.dir/build.make CMakeFiles/Cyborg.dir/Cyborg.cpp.s
.PHONY : Cyborg.cpp.s

Empire.o: Empire.cpp.o
.PHONY : Empire.o

# target to build an object file
Empire.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Empire.dir/build.make CMakeFiles/Empire.dir/Empire.cpp.o
.PHONY : Empire.cpp.o

Empire.i: Empire.cpp.i
.PHONY : Empire.i

# target to preprocess a source file
Empire.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Empire.dir/build.make CMakeFiles/Empire.dir/Empire.cpp.i
.PHONY : Empire.cpp.i

Empire.s: Empire.cpp.s
.PHONY : Empire.s

# target to generate assembly for a file
Empire.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Empire.dir/build.make CMakeFiles/Empire.dir/Empire.cpp.s
.PHONY : Empire.cpp.s

http.o: http.cpp.o
.PHONY : http.o

# target to build an object file
http.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/http.dir/build.make CMakeFiles/http.dir/http.cpp.o
.PHONY : http.cpp.o

http.i: http.cpp.i
.PHONY : http.i

# target to preprocess a source file
http.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/http.dir/build.make CMakeFiles/http.dir/http.cpp.i
.PHONY : http.cpp.i

http.s: http.cpp.s
.PHONY : http.s

# target to generate assembly for a file
http.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/http.dir/build.make CMakeFiles/http.dir/http.cpp.s
.PHONY : http.cpp.s

kcc.o: kcc.cpp.o
.PHONY : kcc.o

# target to build an object file
kcc.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kcc.dir/build.make CMakeFiles/kcc.dir/kcc.cpp.o
.PHONY : kcc.cpp.o

kcc.i: kcc.cpp.i
.PHONY : kcc.i

# target to preprocess a source file
kcc.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kcc.dir/build.make CMakeFiles/kcc.dir/kcc.cpp.i
.PHONY : kcc.cpp.i

kcc.s: kcc.cpp.s
.PHONY : kcc.s

# target to generate assembly for a file
kcc.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kcc.dir/build.make CMakeFiles/kcc.dir/kcc.cpp.s
.PHONY : kcc.cpp.s

space_clean.o: space_clean.cpp.o
.PHONY : space_clean.o

# target to build an object file
space_clean.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/space_clean.dir/build.make CMakeFiles/space_clean.dir/space_clean.cpp.o
.PHONY : space_clean.cpp.o

space_clean.i: space_clean.cpp.i
.PHONY : space_clean.i

# target to preprocess a source file
space_clean.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/space_clean.dir/build.make CMakeFiles/space_clean.dir/space_clean.cpp.i
.PHONY : space_clean.cpp.i

space_clean.s: space_clean.cpp.s
.PHONY : space_clean.s

# target to generate assembly for a file
space_clean.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/space_clean.dir/build.make CMakeFiles/space_clean.dir/space_clean.cpp.s
.PHONY : space_clean.cpp.s

test_space_clean.o: test_space_clean.cpp.o
.PHONY : test_space_clean.o

# target to build an object file
test_space_clean.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_space_clean.dir/build.make CMakeFiles/test_space_clean.dir/test_space_clean.cpp.o
.PHONY : test_space_clean.cpp.o

test_space_clean.i: test_space_clean.cpp.i
.PHONY : test_space_clean.i

# target to preprocess a source file
test_space_clean.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_space_clean.dir/build.make CMakeFiles/test_space_clean.dir/test_space_clean.cpp.i
.PHONY : test_space_clean.cpp.i

test_space_clean.s: test_space_clean.cpp.s
.PHONY : test_space_clean.s

# target to generate assembly for a file
test_space_clean.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_space_clean.dir/build.make CMakeFiles/test_space_clean.dir/test_space_clean.cpp.s
.PHONY : test_space_clean.cpp.s

tree.o: tree.cpp.o
.PHONY : tree.o

# target to build an object file
tree.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/-tree-.dir/build.make CMakeFiles/-tree-.dir/tree.cpp.o
.PHONY : tree.cpp.o

tree.i: tree.cpp.i
.PHONY : tree.i

# target to preprocess a source file
tree.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/-tree-.dir/build.make CMakeFiles/-tree-.dir/tree.cpp.i
.PHONY : tree.cpp.i

tree.s: tree.cpp.s
.PHONY : tree.s

# target to generate assembly for a file
tree.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/-tree-.dir/build.make CMakeFiles/-tree-.dir/tree.cpp.s
.PHONY : tree.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... uninstall"
	@echo "... -tree-"
	@echo "... Alpha"
	@echo "... Cyborg"
	@echo "... Empire"
	@echo "... cpr"
	@echo "... gmock"
	@echo "... gmock_main"
	@echo "... gtest"
	@echo "... gtest_main"
	@echo "... http"
	@echo "... kcc"
	@echo "... libcurl"
	@echo "... space_clean"
	@echo "... test_space_clean"
	@echo "... zlib"
	@echo "... Alpha.o"
	@echo "... Alpha.i"
	@echo "... Alpha.s"
	@echo "... Cyborg.o"
	@echo "... Cyborg.i"
	@echo "... Cyborg.s"
	@echo "... Empire.o"
	@echo "... Empire.i"
	@echo "... Empire.s"
	@echo "... http.o"
	@echo "... http.i"
	@echo "... http.s"
	@echo "... kcc.o"
	@echo "... kcc.i"
	@echo "... kcc.s"
	@echo "... space_clean.o"
	@echo "... space_clean.i"
	@echo "... space_clean.s"
	@echo "... test_space_clean.o"
	@echo "... test_space_clean.i"
	@echo "... test_space_clean.s"
	@echo "... tree.o"
	@echo "... tree.i"
	@echo "... tree.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

